shoppingcart/ShoppingCart.WEB/Areas/Admin/Controllers/CategoryController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using ShoppingCart.BLL.Interfaces;
using ShoppingCart.BLL.ViewModels;

namespace ShoppingCart.WEB.Areas.Admin.Controllers
{
    public class CategoryController : Controller
    {
        readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ActionResult ListCategories(long? parentCategoryId)
        {
            ViewBag.parentCategoryId = parentCategoryId;
            var model = _categoryService.GetAll(parentCategoryId);

            if (!model.Any() && parentCategoryId != null)
                return RedirectToAction("Details", new {parentCategoryId});

            return View(model);
        }

        public ActionResult PartialListChildrenCategory(long? parentCategoryId)
        {
            ViewBag.parentCategoryId = parentCategoryId;
            return PartialView(_categoryService.GetAll(parentCategoryId));
        }

        [HttpGet]
        public async Task<JsonResult> CheckCategoryName(string Name ,long? id)
        {
            if (id == null)//TODO:Это костыль если что!
                id = 0;
            var result = await _categoryService.CheckCategoryName(id.Value,Name);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create(long? parentCategoryId, string redirectStr)
        {
            ViewBag.parentCategoryId = parentCategoryId;
            ViewBag.RedirectStr = redirectStr;
            return View(new CategoryViewModel {ParentCategoryId = parentCategoryId});
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Create(FormCollection a, CategoryViewModel newCategory, string redirectStr)
        {
            var  res = await _categoryService.Create(newCategory);

            if (res.Succedeed)
                return RedirectToAction(redirectStr, new {parentCategoryId = newCategory.ParentCategoryId});

            ViewBag.RedirectStr = redirectStr;
            ViewBag.Error = res.Message + $"  {res.Property}";
            return View(newCategory);
        }

        public ActionResult Edit(long id, string redirectStr)
        {
            ViewBag.RedirectStr = redirectStr;
            var model = _categoryService.GetById(id);
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(CategoryViewModel category, string redirectStr)
        {
            var res = await _categoryService.Update(category);

            if (res.Succedeed)
                return RedirectToAction(redirectStr, new { parentCategoryId = category.ParentCategoryId });

            ViewBag.RedirectStr = redirectStr;
            ViewBag.Error = res.Message + $"  {res.Property}";
            return View(category);
        }

        public ActionResult Details(long? parentCategoryId, string nameCategory)
        {
            if (parentCategoryId == null)
                parentCategoryId = 0;

            ViewBag.NameCategory = _categoryService.GetById(parentCategoryId.Value).Name;

            return View(parentCategoryId);
        }

        public async Task<ActionResult> Delete(long id)
        {
            await _categoryService.Delete(id);
            return View();
        }
    }
}

shoppingcart/ShoppingCart.WEB/Areas/Admin/Controllers/CharacteristicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ShoppingCart.BLL.Interfaces;
using ShoppingCart.BLL.ViewModels;

namespace ShoppingCart.WEB.Areas.Admin.Controllers
{
    public class CharacteristicController : Controller
    {
        readonly ICharacteristicService _characteristicService;
        public CharacteristicController(ICharacteristicService characteristicService)
        {
            _characteristicService = characteristicService;
        }

        public ActionResult PartialCharacteristicList(long parentCategoryId)
        {
            ViewBag.parentCategoryId = parentCategoryId;
            var model = _characteristicService.GetAll(parentCategoryId).ToList();
            return View(model);
        }

        public ActionResult Details(long id)
        {
            var model = _characteristicService.GetById(id);
            return View(model);
        }

        [HttpGet]
        public JsonResult CheckCategoryName(string Name, long Id = 0)
        {
            return Json(_characteristicService.CheckCharacteristicName(Name, Id), JsonRequestBehavior.AllowGet);
        }
        //TODO:---> Переделать все "public ActionResult Delete" на Post <---
        public ActionResult Delete(long id,long parentCategoryId)
        {
            _characteristicService.Delete(id);
            return RedirectToAction("Details", "Category", new { parentCategoryId });
        }

        public ActionResult Create(long parentCategoryId)
        {
            var model = new CharacteristicViewModel
            {
                ParentCategoryId = parentCategoryId
            };

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(CharacteristicViewModel newCharacteristic)
        {
            var res = await _characteristicService.Create(newCharacteristic);

            if(res.Succedeed)
                return RedirectToAction("Details", "Category", new { parentCategoryId = newCharacteristic.ParentCategoryId});

            ViewBag.Error = res.Message + $"  {res.Property}";
            return View(newCharacteristic);
        }

        public ActionResult Edit(long id)
        {
            var model = _characteristicService.GetById(id);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(CharacteristicViewModel newCharacteristic)
        {
            var res = await _characteristicService.Update(newCharacteristic);

            if(res.Succedeed)
                return RedirectToAction("Details", "Category", new { parentCategoryId = newCharacteristic.ParentCategoryId });

            ViewBag.Error = res.Message + $"  {res.Property}";
            return View(newCharacteristic);
        }
    }
}

shoppingcart/ShoppingCart.WEB/Areas/Admin/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ShoppingCart.BLL.Interfaces;
using ShoppingCart.BLL.ViewModels;

namespace ShoppingCart.WEB.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public ActionResult PartialListOfProduct(long parentCategoryId)
        {
            ViewBag.ParentCategoryId = parentCategoryId;
           var model = _productService.GetAll(parentCategoryId);
            return View(model);
        }
        //TODO:всплывающий тайтл если удалить нельзя

        #region Create region
        public ActionResult Create(long parentCategoryId)
        {
            ViewBag.ParentCategoryId = parentCategoryId;
            //var characteristics = _productService.GetAllCharacteristic(parentCategoryId).ToList();
            //var model = new ProductViewModel {Characteristics = characteristics, ParentCategoryId = parentCategoryId};
            return View();
        }

        public ActionResult PartialProductCreate(long parentCategoryId)
        {
            var model = new ProductCreateViewModel {  ParentCategoryId = parentCategoryId };
            return View(model);
        }

        public ActionResult PartialCreatePhoto(long parentCategoryId)
        {
            return View();
        }

        public ActionResult PartialCreateCharecteristic(long parentCategoryId)
        {
            var characteristics = _productService.GetAllCharacteristic(parentCategoryId).ToList();
            return View(characteristics);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Create(ProductCreateViewModel product, HttpPostedFileBase[] uploadImage, List<CharacteristicValueViewModel> listCharacteristicValue, string[] aspectRatio)
        {
            var photoes = uploadImage.Where(pic => pic != null).Select((pic, r) => new PhotoViewModel
            {
                OriginalPhoto = pic,
                AspectRatio = aspectRatio[r]
            }).ToList();

            await _productService.Create(product, photoes, listCharacteristicValue ?? new List<CharacteristicValueViewModel>());
            return RedirectToAction("Details", "Category", new { parentCategoryId = product.ParentCategoryId });

        }
        #endregion

        #region Edit
        public ActionResult Edit(long id, long parentCategoryId)
        {
            ViewBag.ProductId = id;
            ViewBag.ParentCategoryId = parentCategoryId;
        
            var viewModel = new ProductUpdateViewModel
            {
                EditProduct = _productService.GetByIdForUpdate(id, parentCategoryId),
                Characteristics = _productService.GetCharacteristicForProduct(id, parentCategoryId).ToList(),
                OldPhotoes = _productService.GetPhotoForProduct(id).ToList()
            };

            return View(viewModel);
        }

        public ActionResult PartialEditProduct(ProductCreateViewModel viewModelProduct)
        {
            return View(viewModelProduct);
        }

        public ActionResult PartialEditCharecteristic(List<CharacteristicValueViewModel> viewModelCharecteristic)
        {
            return View(viewModelCharecteristic);
        }

        public ActionResult PartialEditPhotoes(List<PhotoProductViewModel> viewModelPhotoes)
        {
            return View(viewModelPhotoes);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(ProductCreateViewModel editProduct, List<CharacteristicValueViewModel> characteristics, List<PhotoProductViewModel> oldPhotoes, HttpPostedFileBase[] newPhotoes, string[] aspectRatioNewPhotoes)
        {
            var photoes = newPhotoes.Where(pic => pic != null).Select((pic, r) => new PhotoViewModel
            {
                OriginalPhoto = pic,
                AspectRatio = aspectRatioNewPhotoes[r]
            }).ToList();

            var viewModel = new ProductUpdateViewModel
            {
                OldPhotoes = oldPhotoes,
                Characteristics = characteristics,
                EditProduct = editProduct,
                NewPhotoes = photoes
            };

            await _productService.Update(viewModel);

            return RedirectToAction("Details", "Category", new { parentCategoryId = editProduct.ParentCategoryId });
        }
        #endregion

        public async Task<ActionResult> Delete(long id, long parentCategoryId)
        {
            await _productService.Delete(id);
            return RedirectToAction("Details", "Category", new { parentCategoryId = parentCategoryId });
        }
		public ActionResult Details(long id, long parentCategoryId)
		{
			var viewMdoel = _productService.GetById(id, parentCategoryId);
			return View(viewMdoel);
		}

	}
}
//TODO:Сделать пагинацию для таблиц

shoppingcart/ShoppingCart.WEB/Areas/Admin/Views/Category/Create.cshtml
@model ShoppingCart.BLL.ViewModels.CategoryViewModel

@{
    ViewBag.Title = "Создание категории";
}
<script src="//cdn.ckeditor.com/4.5.9/basic/ckeditor.js"></script>
<h2>Создание новой категории</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <br />
        <h4 class="text-danger field-validation-error"><b>@ViewBag.Error</b></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ParentCategoryId)
        <div class="form-group">
            @Html.Label("Название категории *", htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Discription, new { @id = "Discription", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Discription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Publish, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="margin-top: 14px">
                <div class="material-switch">
                    <input id="PublishSwitch" name="Publish" type="checkbox" value="true" @(Model.Publish ? "checked=\"checked\"" : "") />
                    <label for="PublishSwitch" class="label-success"></label>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="create-category" value="Создать" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("К списку", ViewBag.RedirectStr as string, new {parentCategoryId = Model.ParentCategoryId}, new {@class = "label label-default"})
</div>

@section scripts{

    <script>CKEDITOR.replace("Discription");</script>
}

shoppingcart/ShoppingCart.WEB/Areas/Admin/Views/Category/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

shoppingcart/ShoppingCart.WEB/Areas/Admin/Views/Category/Details.cshtml
@model long?


@{
    ViewBag.Title = "Details";
}



<div class="container">
    <h2>Категория: @ViewBag.NameCategory</h2>
    <hr/>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Подкатегории</h4>
                </div>
                <div class="panel-body">
                    @Html.Action("PartialListChildrenCategory", new {parentCategoryId = @Model})
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Характеристики</h4>
                </div>
                <div class="panel-body">
                    @Html.Action("PartialCharacteristicList", "Characteristic", new {parentCategoryId = @Model})
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Товары</h4>
                </div>
                <div class="panel-body">
                    @Html.Action("PartialListOfProduct", "Product", new {parentCategoryId = @Model})
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>CKEDITOR.replace("Discription");</script>
}

shoppingcart/ShoppingCart.WEB/Areas/Admin/Views/Category/Edit.cshtml
@model ShoppingCart.BLL.ViewModels.CategoryViewModel

@{
    ViewBag.Title = "Редактирование";
}
<script src="//cdn.ckeditor.com/4.5.9/basic/ckeditor.js"></script>
<h2>Редактирование категории: "@Model.Name"</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ParentCategoryId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">

            @Html.LabelFor(model => model.Discription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Discription, new { @id = "Discription", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Discription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Publish, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="margin-top: 14px">
                <div class="material-switch">
                    <input id="PublishSwitch" name="Publish" type="checkbox" value="true" @(Model.Publish ? "checked=\"checked\"" : "") />
                    <label for="PublishSwitch" class="label-success"></label>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("К списку", ViewBag.RedirectStr as string, new { parentCategoryId = Model.ParentCategoryId }, new { @class = "label label-default" })
</div>

@section scripts{
    <script>CKEDITOR.replace("Discription");</script>
}

shoppingcart/ShoppingCart.WEB/Areas/Admin/Views/Category/ListCategories.cshtml
@model IEnumerable<ShoppingCart.BLL.ViewModels.CategoryViewModel>

@{
    ViewBag.Title = "List";
}

    @*<div class="row">
        <div class="popupunder alert alert-danger fade in"><button type="button" class="close close-sm" data-dismiss="alert"><i class="glyphicon glyphicon-remove"></i></button><strong>Success : </strong> The update process has been completed successfull!</div>
    </div>*@

    @*<div class="row">
        <div class="popupunder alert alert-danger fade in">
            <button type="button" class="close close-sm" data-dismiss="alert">
                <i class="glyphicon glyphicon-remove"></i>
            </button><strong>Success : </strong> The update process has been completed successfull!
        </div>
    </div>*@
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2>Ктегории</h2>

                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                            <tr>
                                <th>
                                    @Html.Label("Название категории", new { @class = "h4" })
                                </th>
                                <th>
                                    @Html.ActionLink("Создать новую", "Create", new { parentCategoryId = ViewBag.parentCategoryId, redirectStr = "ListCategories" }, new { @class = "label label-success pull-right" })
                                </th>
                            </tr>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.ActionLink(item.Name, "ListCategories", new { parentCategoryId = item.Id }, new { @class = "label label-primary" })
                                    </td>
                                    <td>
                                        @Html.ActionLink("Подробнее", "Details", new { parentCategoryId = item.Id, nameCategory = item.Name }, new { @class = "label label-info" }) <b>|</b>
                                        @Html.ActionLink("Редактировать", "Edit", new { id = item.Id, redirectStr = "ListCategories" }, new { @class = "label label-warning" })
                                        @Html.ActionLink("Удалить", "Delete", new { id = item.Id, redirectStr = "ListCategories" }, new { @class = "label label-warning" })
                                    </td>
                                </tr>
                            }

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    @section scripts
{
        <script>
            $('.popovers').popover();
            window.setTimeout(function () {
                $(".alert").fadeTo(2000, 500).slideUp(500, function () {
                    $(this).remove();
                });
                // 500 : Time will remain on the screen
            }, 500);
        </script>
    }

shoppingcart/ShoppingCart.WEB/Areas/Admin/Views/Category/PartialListChildrenCategory.cshtml
@model IEnumerable<ShoppingCart.BLL.ViewModels.CategoryViewModel>
    @*TODO:Удалить*@

@{
    Layout = null;
}

<div class="table-responsive">
    <div class="table table-striped table-bordered table-hover">
        <table class="table">
            <tr>
                <th>
                    <div class="h5">
                        <b>Название категории</b>
                    </div>
                </th>
                <th>
                    @Html.ActionLink("Создать новую", "Create", new { parentCategoryId = ViewBag.parentCategoryId, redirectStr = "Details" }, new {@class="pull-right label label-success"})
                </th>
            </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.ActionLink("Редактировать", "Edit", new { id = item.Id, redirectStr = "Details" }, new { @class = "label label-warning" }) <b>|</b>
                            @Html.ActionLink("Подробнее", "Details", new { parentCategoryId = item.Id }, new { @class = "label label-info" })
                        </td>
                    </tr>
                }
        </table>

    </div>
</div>

shoppingcart/ShoppingCart.WEB/Areas/Admin/Views/Category/PartialListProduct.cshtml
@model IEnumerable<ShoppingCart.BLL.ViewModels.CategoryViewModel>
@*TODO:Удалить*@
<p>
    @Html.ActionLink("Create New", "Index", "Product")
</p>
<div class="table-bordered">
    <table class="table table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new {id = item.Id}) <b>|</b>
                    @*@Html.ActionLink("Details", "Details", new {id = item.Id})<b>|</b>*@
                    @Html.ActionLink("Удалить", "Delete", new {id = item.Id}, new {@class = "label label-danger disabled"})
                </td>
            </tr>
        }

    </table>
</div>