shoppingcart/ShoppingCart.WEB/Areas/Admin/Controllers/CategoryController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using ShoppingCart.BLL.Interfaces;
using ShoppingCart.BLL.ViewModels;

namespace ShoppingCart.WEB.Areas.Admin.Controllers
{
    public class CategoryController : Controller
    {
        readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ActionResult ListCategories(long? parentCategoryId)
        {
            ViewBag.parentCategoryId = parentCategoryId;
            var model = _categoryService.GetAll(parentCategoryId);

            if (!model.Any() && parentCategoryId != null)
                return RedirectToAction("Details", new {parentCategoryId});

            return View(model);
        }

        public ActionResult PartialListChildrenCategory(long? parentCategoryId)
        {
            ViewBag.parentCategoryId = parentCategoryId;
            return PartialView(_categoryService.GetAll(parentCategoryId));
        }

        [HttpGet]
        public async Task<JsonResult> CheckCategoryName(string Name ,long? id)
        {
            if (id == null)//TODO:Это костыль если что!
                id = 0;
            var result = await _categoryService.CheckCategoryName(id.Value,Name);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create(long? parentCategoryId, string redirectStr)
        {
            ViewBag.parentCategoryId = parentCategoryId;
            ViewBag.RedirectStr = redirectStr;
            return View(new CategoryViewModel {ParentCategoryId = parentCategoryId});
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Create(FormCollection a, CategoryViewModel newCategory, string redirectStr)
        {
            var  res = await _categoryService.Create(newCategory);

            if (res.Succedeed)
                return RedirectToAction(redirectStr, new {parentCategoryId = newCategory.ParentCategoryId});

            ViewBag.RedirectStr = redirectStr;
            ViewBag.Error = res.Message + $"  {res.Property}";
            return View(newCategory);
        }

        public ActionResult Edit(long id, string redirectStr)
        {
            ViewBag.RedirectStr = redirectStr;
            var model = _categoryService.GetById(id);
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(CategoryViewModel category, string redirectStr)
        {
            var res = await _categoryService.Update(category);

            if (res.Succedeed)
                return RedirectToAction(redirectStr, new { parentCategoryId = category.ParentCategoryId });

            ViewBag.RedirectStr = redirectStr;
            ViewBag.Error = res.Message + $"  {res.Property}";
            return View(category);
        }

        public ActionResult Details(long? parentCategoryId, string nameCategory)
        {
            if (parentCategoryId == null)
                parentCategoryId = 0;

            ViewBag.NameCategory = _categoryService.GetById(parentCategoryId.Value).Name;

            return View(parentCategoryId);
        }

        public async Task<ActionResult> Delete(long id)
        {
            await _categoryService.Delete(id);
            return View();
        }
    }
}

shoppingcart/ShoppingCart.WEB/Areas/Admin/Controllers/PanelController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using ShoppingCart.BLL.DTO;
using ShoppingCart.BLL.Interfaces;
using ShoppingCart.WEB.CustomAttrinutes;

namespace ShoppingCart.WEB.Areas.Admin.Controllers
{
    [CustomAuthorization(Url = "/Account/LoginAdmin")]
    public class PanelController : Controller
    {
        public async Task<ActionResult> Index()
        {
            return View();
        }
    }
}

shoppingcart/ShoppingCart.WEB/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" type="text/css" href="~/Content/Admin/AdminNav.css">
    <link rel="stylesheet" href="~/Content/font-awesome.min.css">
    @RenderSection("css", false)
    <meta name="description" content="The description of my page" />
</head>
<body>

<div id="wrapper">
    <!-- Навигация -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Бренд и кнопка меню для моб-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand"><b>Shopping Cart </b></a>
        </div>
        <!-- Верхнее меню -->
        <ul class="nav navbar-right top-nav">

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="#">Admin <span class="label label-default">Поправить футер</span></a>
                    </li>
                    <li>
                        <a href="#">Manager <span class="label label-primary">Проверить категори</span></a>
                    </li>
                    <li>
                        <a href="#">Boss<br/> <span class="label label-success">Зарплата</span></a>
                    </li>
                    <li>
                        <a href="#">Manager <span class="label label-danger">Удалить фото</span></a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">Просмотреть все</a>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Aleks Podporinov <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="#"><i class="fa fa-fw fa-user"></i> Профиль</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-fw fa-gear"></i> Настройки</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#"><i class="fa fa-fw fa-power-off"></i> Выйти</a>
                    </li>
                </ul>
            </li>
        </ul>
        <!--Сайд бар(боковое меню)-->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav side-nav">
                <li class="url-act"><a href="@Url.Action("Index", "Panel", new {id = 15})"><i class="fa fa-bar-chart"></i> Главная</a></li>
                <li class="url-act">
                    <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-tasks"></i> Каталоги <i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="demo" class="collapse">
                        <li class="url-act">
                            <a href="@Url.Action("ListCategories", "Category")"> Категории</a>
                        </li>
                        <li class="url-act">
                            <a href="@Url.Action("Index", "Panel", new { id = 10})"> Товары</a>
                        </li>
                        <li class="url-act">
                            <a href="@Url.Action("Index", "Panel", new { id = 2})"> Товары</a>
                            @*<a href="#"> Характеристики</a>*@
                        </li>
                    </ul>
                </li>
                <li class="url-act"><a href="@Url.Action("Index", "Panel", new { id = 3})"><i class="fa fa-shopping-bag"></i> Продажи</a></li>
                <li class="url-act"><a href="@Url.Action("Index", "Panel", new { id = 4})"><i class="fa fa-users"></i> Пользователи</a></li>
                <li class="url-act"><a href="@Url.Action("Index", "Panel", new { id = 5})"><i class="fa fa-tags"></i> Акции</a></li>
                <li class="url-act"><a href="@Url.Action("Index", "Panel", new { id = 6})"><i class="fa fa-cubes"></i> Управление контентом</a></li>
                <li class="url-act"><a href="@Url.Action("Index", "Panel", new { id = 7})"><i class="fa fa-cube"></i> Система</a></li>
                <li class="url-act"><a href="@Url.Action("Index", "Panel", new { id = 8})"><i class="fa fa-question-circle"></i> Помощь</a></li>
                @*<li class="url-act">
                    <a href="@Url.Action("ListCategories", "Category")"> Категории</a>
                </li>*@
            </ul>
        </div>
    </nav>
    <div id="page-wrapper">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </div>
    <footer class="panel-footer">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>
            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/jqueryval")
            @Scripts.Render("~/bundles/modernizr")
            @Scripts.Render("~/bundles/bootstrap")
<script> 
    var local = location.href;

    $(".nav li").on("click", function () {
        $(".nav li").removeClass("active");
    });

    $(".url-act").each(function (index) {
        var li = this;
        $(this).find("a").each(function() {
            $(this).parent().removeClass('active');
            if (local === this.href) {
                

                if ($(li).parent()[0].id === "demo") {
                    $($(li).parent()[0]).addClass("in");
                    $(li).addClass("active-menu");
                }
                console.log(location.href + " - location.href");
                console.log(this.href + " - this.href");
                $(li).addClass("active");

            }
        });
    });


    //$('ul.categories a').each(function () {
    //    if (this.href == location.href) $(this).parent().addClass('active');
    //});

   
</script>
            @RenderSection("scripts", required: false)
    </body>
    </html>

shoppingcart/ShoppingCart.WEB/Areas/Admin/Views/Shared/_modalInfo.cshtml
@section css {
    <link href="@Url.Content("~/Content/ModalInfoHeadings.css")" rel="stylesheet" />
}
<!-- Modal success-->
    <div class="modal fade" id="modal-success" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header modal-header-success">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h1><i class="glyphicon glyphicon-thumbs-up"></i> Success Modal</h1>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Modal -->

    <!-- Modal primary-->
    <div class="modal fade" id="modal-primary" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header modal-header-primary">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h1><i class="glyphicon glyphicon-thumbs-up"></i> Primary Modal</h1>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Modal -->
   
    <!-- Modal info-->
    <div class="modal fade" id="modal-info" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header modal-header-info">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h1><i class="glyphicon glyphicon-thumbs-up"></i> Info Modal</h1>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Modal -->
  
    <!-- Modal warning-->
    <div class="modal fade" id="modal-warning" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header modal-header-warning">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h1><i class="glyphicon glyphicon-thumbs-up"></i> Warning Modal</h1>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Modal -->
    
    <!-- Modal danger-->
    <div class="modal fade" id="modal-danger" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header modal-header-danger">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h1><i class="glyphicon glyphicon-thumbs-up"></i> Danger Modal</h1>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Modal -->